### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by bararchy** [Sdogruyol/cryload#1]
1) --help \ -h to print usage would be cool
2) Right now (if i'm not mistaken) you are using a single channel to generate the connections, it could be cool to initialize "threads" (channels) with a -c or -t so we can do a more massive load.
3) Is there an option to indicate the numbers or requests ? if not a -r will be cool :)

**Comment by sdogruyol** [comment]
1) I agree on that :)

2) Currently i'm using 1 channel to generate the connections. And channels are single threaded that's why it's a bottleneck. We can do something like spawning another process and piping the result back.

3) Actually you can specify the numbers like ./cryload http://www.example.com 10000 but -r will be better :+1:

**Comment by sdogruyol** [comment]
@bararchy Updated README btw

**Comment by bararchy** [comment]
@Sdogruyol cool, now it's easier to understand how to control requests :) 

Also, when I finished a scan I got this output:

```
./cryload http://172.16.1.1/ 1000
"Preparing to make it CRY for 1000 requests!"
"Total request made: 100"
"Total request made: 200"
"Total request made: 300"
"Total request made: 400"
"Total request made: 500"
"Total request made: 600"
"Total request made: 700"
"Total request made: 800"
"Total request made: 900"
"COMPLETED"
"Minimum time taken per request 2.932 ms"
"Maximum time taken per request 8.62 ms"
"Average time taken per request: 3.226 ms"
"Request per second: 309.95"
"Total request made: 1000"
"Total time taken: 3.22632 seconds"
```

I don't know why but the " before and after each sentence looks bad (for me), maybe don't print them ? I think it will make the output more clear.

Also, what about using Colorize ? it could be cool :)

**Comment by sdogruyol** [comment]
I haven't spent much time on logging and it really needs a makeup :sunny:
