### ISSUE TITLE
HTTP::Client Wont support SSL

### ISSUE THREAD

**Issue by bararchy** [Sdogruyol/cryload#4]
1) It wont automatically set port to 443 if the URI begins with https://
2) when specified :443 in URI it wont negotiate SSL connection

**Comment by sdogruyol** [comment]
I'm aware of that maybe we should handle it by parsing the URI

**Comment by sdogruyol** [comment]
Btw is this related to Crystal std?

**Comment by sdogruyol** [comment]
Btw i just gave this a try like below

`./cryload -s https://www.google.com.tr -r 1000`

And it was okay. What's the uri you trying ?

**Comment by bararchy** [comment]
@Sdogruyol it tries to connect to google.com on port 80, and it works, but, looks at this: 

```
 ./cryload --server https://192.168.1.232/ -r 1000                                                     :(
Preparing to make it CRY for 1000 requests!
Unhandled exception: Error connecting to '192.168.1.232:80': Connection refused
```

**Comment by sdogruyol** [comment]
Is it something DNS related or what? It's pretty strange that it tries to connect to port 80 https lol

**Comment by bararchy** [comment]
@Sdogruyol I suspect its an issue in Up-stream crystal std libs, we can open an issue

**Comment by sdogruyol** [comment]
Want me to open it ?

**Comment by bararchy** [comment]
@Sdogruyol Sure, just link the issue in upstream to this issue, so we know what's the issue and when it's fixed :)

**Comment by sdogruyol** [comment]
Guess i find the root of the problem it's URI.parse related

https://github.com/Sdogruyol/cryload/blob/master/src/cryload.cr#L20-L22

**Comment by waj** [comment]
You need to specify the "ssl" parameter while creating the HTTP::Client. Something like this:

``` crystal
client = HTTP::Client.new uri.host.not_nil!, port: uri.port, ssl: uri.scheme == "https"
```

**Comment by sdogruyol** [comment]
What if i pass the scheme from URI.parse does it handle this ?

**Comment by waj** [comment]
BTW... it worked fine with "https://www.google.com.tr/" because Google also has port 80 open ;-)

**Comment by sdogruyol** [comment]
Ah yeah you are right :+1:

**Comment by waj** [comment]
HTTP::Client will connect to port 80 or 443 (depending on the ssl parameter) unless another port is specified. URI#port is nil unless there is an explicit port specified in the URI string.

**Comment by sdogruyol** [comment]
So i think getting the scheme from URI.parse will solve this issue :+1:

**Comment by sdogruyol** [comment]
Thanks @waj

**Comment by sdogruyol** [comment]
Hey @bararchy can you rerun the test with head please :)

**Comment by waj** [comment]
@Sdogruyol you're welcome!
Please close manastech/crystal#1089 once you know this fixed the issue.

**Comment by sdogruyol** [comment]
Sure @waj thanks alot :+1:

**Comment by bararchy** [comment]
@Sdogruyol Works like charm ;) 

```
./cryload -s https://127.0.0.1/ -n 50
Preparing to make it CRY for 50 requests!
Unhandled exception: Error connecting to '127.0.0.1:443': Connection refused
```
