### ISSUE TITLE
Duration V.S Requests

### ISSUE THREAD

**Issue by bararchy** [Sdogruyol/cryload#5]
Just a point for thought, 
We have two known tools for http stressing, ab (apachi-benchmark) and wrk, they each work differently

wrk - work using duration, as in, you set the duration, threads and connections, and the tool will try to reach the most requests per sec using the threads and connections you configured.

ab - works like cryload, as in you set how much connections you want to create, and it tries to do those as fast as possible.

I think having both duration and requests is UN-needed, we just need to decide upon a certain value to work with

**Comment by sdogruyol** [comment]
Actually i prefer `ab` style.

Let's do it that way meaning we don't need duration.
