### ISSUE TITLE
Multi-Fibering

### ISSUE THREAD

**Issue by bararchy** [Sdogruyol/cryload#7]
So, 

I want to tackle this issue, I was thinking about a way to do this and the best idea is (in my opinion) to ask the user to supply -t (threads) or -w (workers), we can the initiate the number of workers to handle the requests and start bombarding the server.

We can use the basic Idea the @waj has suggested here: http://stackoverflow.com/questions/30853566/crystal-convert-the-idea-behind-thread-pool-to-fibers-spawn

what do you think ?

**Comment by sdogruyol** [comment]
Well i also want to tackle this but it's pretty interesting when combined with channels :+1:

**Comment by sdogruyol** [comment]
So does doing something like below is a way to go about this?

``` crystal
worker_count.times do
  spawn do
    loop do
      client.get
      ....
    end
  end
end
```

**Comment by bararchy** [comment]
``` crystal
ch = Channel(HTTP::Client).new
uri = URI.parse @host
client = HTTP::Client.new uri.host.not_nil!, port: uri.port, ssl: uri.scheme == "https"
workers_count.times do
  spawn do
    loop do
      client = ch.receive
      start_time = Time.now
      response = client.get uri.full_path
      end_time = Time.now
      request = Request.new start_time, end_time, response.status_code
      @stats.requests << request
    end
  end
end

loop do
  ch.send client
end

```

Or something like that

**Comment by sdogruyol** [comment]
Meanwhile a quick try like below didn't improve the performance

``` crystal
10.times do
   spawn do
      loop do
        start_time = Time.now
        response = client.get uri.full_path
        end_time = Time.now
        request = Request.new start_time, end_time, response.status_code
        @stats.requests << request
        channel.send nil
      end
    end
 end
```

**Comment by sdogruyol** [comment]
We don't have to send client through channel

**Comment by sdogruyol** [comment]
Guess the event loop is the bottleneck here //cc @asterite @waj

**Comment by bararchy** [comment]
@Sdogruyol Right now, it will still work with a single Thread, so not too much of a performance boost, but, when @waj and @asterite will finish the Thread pool thingy around channels we will see a massive Thread boost.

Also, in your example you do no create the workers efficiently, as the Workers start and then Die when they finished, in my example (that need more work) I create the workers, then just pass the "work load" on and they finish the work and go on to waiting for more load.

**Comment by sdogruyol** [comment]
What do you mean by worker?

**Comment by bararchy** [comment]
@Sdogruyol workers == Fibers (or channels if you want) every `spawn` call will create a Fiber ready to do our biding, what my code example did (based on @waj example) is to first initiate n Fibers, then, just pass on the work load (as in client.get) while I continue on with the requests

**Comment by sdogruyol** [comment]
Ah yeah you are right actually i wish channels did handle this like in Go :+1: (Multithread by default :chart: )

**Comment by bararchy** [comment]
@Sdogruyol I'm working on it ;) it's a little tricky , not sure why but it just hangs... we need some super pro here, lets see if waj or astr will help

**Comment by bararchy** [comment]
@sdogruyol Guess they never did hahaha
Any way, I was thinking about doing the following

main bin is a wrapper for commands, 
```
cryload -s url -c 2 -n 50  
  - Process.new(mini_cryload -s url -n 50)  
  - Process.new(mini_cryload -s url -n 50)  
```
What do you think ?

**Comment by sdogruyol** [comment]
@bararchy that's interesting. However do we need this? Once parallelism is in Crystal core it'll be multi-threaded by default

**Comment by bararchy** [comment]
@sdogruyol Do we count on that happening in the near future ? XD

**Comment by sdogruyol** [comment]
@bararchy for sure. I think parallelism will be in Crystal 0.25.0 😄  (this is a total guess)

**Comment by bararchy** [comment]
If so then I'm closing this.
